version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: url_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: url_redis
    restart: always
    ports:
      - "6380:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  pgdata:
